jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach-workspace:
          at: tmp/workspace
      - run:
          name: The First test
          command: 
            gradle test
      - store_test_results:
          path: build/test-results
      - persist-to-workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach-workspace: 
          at: .
      - run:
          name: The First build
          command: 
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist-to-workspace:
          root: .
          paths: 
            - .

workflows:
  version: 2
  two-job-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
          