workflows:
  version: 2.0
  test-of-2-jobflow:
    jobs:
      test:
        docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run:
              name: The First test
              command: 
                gradle test
          - store_test_results:
              path: build/test-results
      package:
        docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run:
              name: The First package
              command: 
                gradle jar
          - store_artifacts:
              path: build/libs
            destination: prefix

